### ISSUE TITLE
Viz: IndexError thrown

### ISSUE THREAD

**Issue by TanjaSmiley** [bit-bots/dynamic_stack_decider#18]
Rqt died with throwing an IndexError when using the body_behavior DSD Viz, the rviz behavior test launch script from  the humanoid_league_interactive_marker package and the behavior launch script:
```
Traceback (most recent call last):
  File "/home/tanja/RoboCup_ws/src/bitbots_meta/dynamic_stack_decider/dynamic_stack_decider_visualization/src/dynamic_stack_decider_visualization/dsd_visualization_plugin.py", line 154, in timerEvent
    self.refresh()
  File "/home/tanja/RoboCup_ws/src/bitbots_meta/dynamic_stack_decider/dynamic_stack_decider_visualization/src/dynamic_stack_decider_visualization/dsd_visualization_plugin.py", line 174, in refresh
    self._render_debug_data(self.dsd.to_QItemModel())
  File "/home/tanja/RoboCup_ws/src/bitbots_meta/dynamic_stack_decider/dynamic_stack_decider_visualization/src/dynamic_stack_decider_visualization/dsd_slave.py", line 264, in to_QItemModel
    elem, _ = self.stack[i]
IndexError: list index out of range
```

**Comment by SammyRamone** [comment]
The error did not seem to have happened again. We also fixed multiple issues in the viz in between, so I assume that this can be closed
